---
- name: check zabbix plugin scripts directory
  stat: path={{ zabbix_mongodb_plugin_dir }}
  register: exists_plugin_dir

- name: create zabbix directory
  file: path={{ zabbix_mongodb_plugin_dir }} state=directory
  when: exists_plugin_dir.isdir is not defined

- name: install zabbix sender
  yum: name=zabbix-sender state=present

- name: install php-pecl-mongo
  yum: 
    name:
      - php-pecl-mongo
      - php-cli
    enablerepo: remi-php56 
    state: present
  ignore_errors: "{{ ansible_check_mode }}"

- name: copy plugin files
  copy: src=files/mikoomi-zabbix-mongodb-monitoring/mongodb-{{ zabbix_mongodb_mongodb_version }}/{{ item }} dest={{ zabbix_mongodb_plugin_dir }} mode=555
  with_items:
    - mikoomi-mongodb-plugin-{{ zabbix_mongodb_mongodb_version | replace ('.', '') }}.php
    - mikoomi-mongodb-plugin-{{ zabbix_mongodb_mongodb_version | replace ('.', '') }}.sh

- name: copy script wrapper
  template: src=wrapper.sh.j2 dest={{ zabbix_mongodb_plugin_dir }}wrapper.sh mode=550 owner=zabbix group=zabbix

- name: install cron for zabbix sender
  cron:
    name: zabbix mongodb monitoring
    user: zabbix
    job: "{{ zabbix_mongodb_plugin_dir }}wrapper.sh"
